- name: Home
  columns:
    - size: small
      widgets:
        - type: monitor
          cache: 8m
          title: Media frontends
          sites:
            - title: jellyfin
              url: https://jellyfin.${GROUND_DOMAIN}
              icon: /assets/icons/jellyfin.svg
            - title: Seerr
              url: https://seerr.${GROUND_DOMAIN}
              icon: /assets/icons/seerr.svg
            - title: Shelfmark
              url: https://shelfmark.${GROUND_DOMAIN}
              icon: /assets/icons/shelfmark.svg

        - type: monitor
          cache: 8m
          title: Privacy frontends
          sites:
            - title: Anonymous overflow
              url: https://anonymous-overflow.${GROUND_DOMAIN}
              icon: /assets/icons/anonymousoverflow.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
            - title: Breezewiki
              url: https://breezewiki.${GROUND_DOMAIN}
              icon: /assets/icons/fandom.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}

        - type: monitor
          cache: 8m
          title: Monitoring
          sites:
            - title: Beszel
              url: https://beszel.${GROUND_DOMAIN}
              icon: /assets/icons/beszel/icon.svg
            - title: Speedtest
              url: https://speedtest.${GROUND_DOMAIN}
              icon: /assets/icons/speedtest.svg
            - title: Tracearr
              url: https://tracearr.${GROUND_DOMAIN}
              icon: /assets/icons/tracearr.svg
            - title: MediaLyze
              url: https://medialyze.${GROUND_DOMAIN}
              icon: /assets/icons/medialyze.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}

        - type: monitor
          cache: 8m
          title: ATmosphere
          sites:
            - title: PDS
              url: https://pds.${GROUND_DOMAIN}
              icon: /assets/icons/atproto.svg
            - title: Knot
              url: https://knot.${GROUND_DOMAIN}
              icon: /assets/icons/knot.svg
            - title: Spindle
              url: https://spindle.${GROUND_DOMAIN}
              icon: /assets/icons/spindle.svg

    - size: small
      widgets:
        - type: monitor
          cache: 8m
          title: Sync services
          sites:
            - title: Atuin
              url: https://atuin.${GROUND_DOMAIN}
              icon: /assets/icons/atuin.svg
            - title: Firefox sync
              url: https://firefox-sync.${GROUND_DOMAIN}
              icon: /assets/icons/firefox.svg

        - type: monitor
          cache: 8m
          title: Nix
          sites:
            - title: Nix cache proxy
              url: https://ncps.${GROUND_DOMAIN}
              icon: /assets/icons/ncps.svg
              basic-auth:
                username: nix
                password: ${NCPS_TOKEN}

        - type: monitor
          cache: 8m
          title: files
          sites:
            - title: copyparty
              url: https://copyparty.${GROUND_DOMAIN}
              icon: /assets/icons/copyparty.svg
              basic-auth:
                username: glance
                password: ${authentik_password}
            - title: immich
              url: https://immich.${GROUND_DOMAIN}
              icon: /assets/icons/immich.svg

        - type: monitor
          cache: 8m
          title: Other
          sites:
            - title: Vaultwarden
              url: https://vaultwarden.${GROUND_DOMAIN}
              icon: /assets/icons/vaultwarden.svg
            - title: Authentik
              url: https://authentik.${GROUND_DOMAIN}
              icon: /assets/icons/authentik.svg
            - title: Tiny Tiny RSS
              url: https://ttrss.${GROUND_DOMAIN}
              icon: /assets/icons/tiny-tiny-rss.svg

        - type: monitor
          cache: 8m
          title: Notifications
          sites:
            - title: Gotify
              url: https://gotify.${GROUND_DOMAIN}
              icon: /assets/icons/gotify.svg
            - title: Apprise
              url: https://apprise.${GROUND_DOMAIN}
              icon: /assets/icons/apprise.svg

    - size: full
      widgets:
        - type: monitor
          cache: 8m
          title: Media backend
          sites:
            - title: Prowlarr
              url: https://prowlarr.${GROUND_DOMAIN}
              icon: /assets/icons/prowlarr.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
            - title: Radarr
              url: https://radarr.${GROUND_DOMAIN}
              icon: /assets/icons/radarr.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
            - title: Radarr anime
              url: https://radarr-an.${GROUND_DOMAIN}
              icon: /assets/icons/radarr.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
            - title: Bazarr
              url: https://bazarr.${GROUND_DOMAIN}
              icon: /assets/icons/bazarr.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
            - title: Sonarr
              url: https://sonarr.${GROUND_DOMAIN}
              icon: /assets/icons/sonarr.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
            - title: Sonarr anime
              url: https://sonarr-an.${GROUND_DOMAIN}
              icon: /assets/icons/sonarr.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
            - title: Fileflows
              url: https://fileflows.${GROUND_DOMAIN}
              icon: /assets/icons/fileflows.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
            - title: Profilarr
              url: https://profilarr.${GROUND_DOMAIN}
              icon: /assets/icons/profilarr.svg
            - title: Qui
              url: https://qui.${GROUND_DOMAIN}
              icon: /assets/icons/qui.svg
            - title: Qui sync
              url: https://qui-sync.${GROUND_DOMAIN}
              icon: /assets/icons/qui.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
            - title: Qbittorrent
              url: https://qbittorrent.${GROUND_DOMAIN}
              icon: /assets/icons/qbittorrent.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
            - title: Sabnzbd
              url: https://sabnzbd.${GROUND_DOMAIN}
              icon: /assets/icons/sabnzbd.svg
              basic-auth:
                username: glance
                password: ${AUTHENTIK_PASSWORD}
        - type: monitor
          cache: 8m
          title: Administration
          sites:
            - title: Dockhand
              url: https://dockhand.${GROUND_DOMAIN}
              icon: /assets/icons/dockhand/icon.png
            - title: Cloudbeaver
              url: https://cloudbeaver.${GROUND_DOMAIN}
              icon: /assets/icons/cloudbeaver.svg
            - title: Traefik
              url: https://traefik.${GROUND_DOMAIN}
              icon: /assets/icons/traefik.svg
            - title: CrowdSec
              url: https://app.crowdsec.net/security-engines
              icon: /assets/icons/crowdsec.svg
            - title: Vaultwarden admin
              url: https://vaultwarden.${GROUND_DOMAIN}/admin
              icon: /assets/icons/vaultwarden.svg

        - type: docker-containers
          title: Media backend services
          running-only: false
          hide-by-default: true
          containers:
            media-unpackerr-1:
              format-container-names: true
              description: Automated archive extractions.
              icon: /assets/icons/unpackerr.png
              hide: false
            media-tracearr-db-1:
              name: Timescaledb for Tracearr
              description: Time-series database, used by Tracearr.
              icon: /assets/icons/timescaledb.svg
              hide: false
            media-tracearr-redis-1:
              name: Redis for Tracearr
              description: In-memory data store for caching and queues, used by Tracearr.
              icon: /assets/icons/redis.svg
              hide: false

        - type: docker-containers
          title: Immich backend services
          running-only: false
          hide-by-default: true
          containers:
            immich-machine-learning-1:
              name: Immich machine learning
              description: Smart search, facial recognition, and metadata jobs.
              icon: /assets/icons/immich/icon.svg
              hide: false
            immich-postgres-1:
              name: Postgres for Immich
              description: Database used by Immich.
              icon: /assets/icons/postgresql.svg
              hide: false
            immich-redis-1:
              name: Redis for Immich
              description: In-memory data store for caching and queues, used by Immich.
              icon: /assets/icons/redis.svg
              hide: false
